spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.96.102.168:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 47.96.102.168
    port: 5672
    password: guest
    username: guest    
  jpa:
    show-sql: true
